export const topics = [
  'Emergency Management',
  'Cybersecurity',
  'Artificial Intelligence',
  'Health Care',
  'Immigration',
  'Border Security',
  'Climate',
  'Energy',
  'Federal Workforce',
  'National Security',
  'Trade',
  'Economic Policy',
  'Infrastructure',
  'Equity',
  'Government Efficiency',
  'Law Enforcement',
];

export const topicKeywords: Record<string, string[]> = {
  'Emergency Management': ['emergency management', 'disaster', 'fema', 'homeland security', 'resilience'],
  Cybersecurity: ['cybersecurity', 'cyber security', 'cyber', 'information security', 'ransomware'],
  'Artificial Intelligence': ['artificial intelligence', 'ai', 'machine learning', 'ml', 'automation'],
  'Health Care': ['health care', 'healthcare', 'medical', 'public health', 'hhs', 'cdc'],
  Immigration: ['immigration', 'immigrant', 'immigrantion', 'border crossing', 'asylum'],
  'Border Security': ['border security', 'border patrol', 'customs', 'immigration and customs', 'cbp'],
  Climate: ['climate', 'greenhouse', 'carbon', 'environment', 'climate change'],
  Energy: ['energy', 'electric', 'oil', 'gas', 'renewable', 'power'],
  'Federal Workforce': ['federal workforce', 'federal employees', 'personnel', 'hiring', 'workforce'],
  'National Security': ['national security', 'defense', 'counterterrorism', 'intelligence', 'homeland security'],
  Trade: ['trade', 'tariff', 'commerce', 'exports', 'imports'],
  'Economic Policy': ['economic', 'economy', 'employment', 'tax', 'budget', 'inflation'],
  Infrastructure: ['infrastructure', 'construction', 'transportation', 'broadband', 'roads', 'bridges'],
  Equity: ['equity', 'fairness', 'civil rights', 'inclusion', 'justice'],
  'Government Efficiency': ['efficiency', 'performance', 'streamline', 'reduce burden', 'government efficiency'],
  'Law Enforcement': ['law enforcement', 'police', 'fbi', 'justice', 'criminal justice'],
};
